### ISSUE TITLE
The next (>) button is rendered on top of the chat window

### ISSUE THREAD

**Issue by sapegin** [survivejs/site#103]
![image 2018-06-22 at 8 05 06 pm](https://user-images.githubusercontent.com/70067/41791949-9b2e9f70-7657-11e8-8166-3f223535a33f.png)

Another bug with arrows:

![image 2018-06-23 at 9 30 47 pm](https://user-images.githubusercontent.com/70067/41812968-dc274dbc-772c-11e8-9f61-e1f3e8f58838.png)

We need to get rid of absolute positioning: arrows should never overlap navigation (this will also fix the chat issue).

**Comment by bebraw** [comment]
Yeah, z-index! Maybe we can assign the chat window higher or do something for the arrows.
