### ISSUE TITLE
Tweak home page layout

### ISSUE THREAD

**Issue by sapegin** [survivejs/site#106]
![image 2018-06-25 at 4 09 13 pm](https://user-images.githubusercontent.com/70067/41855132-2ab038d4-7892-11e8-81d8-f2ed433073d9.png)

Something isn't right with breakpoints I guess.

**Comment by bebraw** [comment]
Do you think it would make sense to go with a different style there? The layout flow could become different.

**Comment by sapegin** [comment]
Yes!

1. I think we should separate books and meta (author, etc.)
2. Would be cool to show all three covers at the very top, but I'm afraid with three-column layout columns would be too long.

**Comment by sapegin** [comment]
But maybe you don't need that much text on the homepage?

**Comment by bebraw** [comment]
The copy can be condensed, yeah. I think that will help with a three column layout too.

**Comment by sapegin** [comment]
Cool, then I'll try three-column layout in a branch and you could play with the copy.

**Comment by bebraw** [comment]
Ok, I can rewrite it against your layout. 👍

**Comment by sapegin** [comment]
Ha, I've reported that before — #98 ;-)
