### ISSUE TITLE
Do not wrap aligned images in paragraphs in Markdown

### ISSUE THREAD

**Issue by sapegin** [survivejs/site#110]
Example — book covers on landings:

```html
<p>
  <figure><img src="/8f86c1d07d5536454690030cd1a10b53.png" alt="SurviveJS - Webpack" 
    class="front-cover" width="255" height="329" />
  <figcaption>SurviveJS - Webpack</figcaption></figure>
</p>
...
```

This creates undesired whitespace.

**Comment by bebraw** [comment]
The wrapping comes from the Markdown parser likely. Here's how to do it: https://github.com/GraphQLFinland/site/blob/master/components/Markdown.js . That solution needs to grow to fit the needs of this site, though.

**Comment by sapegin** [comment]
I mean it doesn't make much sense to put cover into Markdown on landings if we override how they look anyway.

**Comment by bebraw** [comment]
That's true. They can live outside of Markdown for sure.
