### ISSUE TITLE
Headers dissappears after hover on largest breakpoint

### ISSUE THREAD

**Issue by Guria** [survivejs/site#19]
http://webm.host/7a5d4/vid.webm

Linux Ubuntu 15.04
Chrome 45.0.2454.85 (64-bit)

Seems browser related bug. Firefox not affected.

**Comment by bebraw** [comment]
Thanks, it's something in Chrome indeed. If I set `opacity: 0` on sibling within a header, it breaks. Weird.

I got rid of opacity and went with `display: none`. This seems to work just fine.
