### ISSUE TITLE
Figure out how to make the site index work on Galaxy S5

### ISSUE THREAD

**Issue by bebraw** [survivejs/site#20]
Sadly Chrome mobile emulation doesn't have a preset matching S5 and there's no way to reproduce this... Maybe there's a better way to repro.

![galaxy_s5](https://cloud.githubusercontent.com/assets/166921/10881853/fe5488ac-816e-11e5-9700-866634584685.png)

**Comment by bebraw** [comment]
By the looks of it, the media query breaks somehow. Hard to say why/how.

**Comment by bebraw** [comment]
If someone has a Galaxy S5, I would appreciate if you could have a look. I revamped the site CSS.

**Comment by rstegg** [comment]
Tested with latest chrome, looks fine:

![2017-04-02_01-02-52](https://cloud.githubusercontent.com/assets/19234385/24585477/38d750f0-1740-11e7-8deb-add45d0bbaa3.png)
