### ISSUE TITLE
atom feed inline html snippets url's invalid

### ISSUE THREAD

**Issue by Munter** [survivejs/site#32]
The atom feed contains html snippets of blog posts that have anchors pointing at relative urls. Since the atom feed is not served from the same place in the file structure these relative url's fail.

See https://github.com/survivejs/site/blob/gh-pages/atom.xml#L1923 as an example

These urls should be rewritten to the full canonical url, since rss feeds are usually read in apps that can't necessarily provide enough context for relative or root-relative urls to work

**Comment by bebraw** [comment]
Hi,

I did an initial pass at it. See the [rss-plugin repo](https://github.com/antwarjs/rss-plugin). If you have time, check out the test cases. I might be missing a test or two but it's a start.

**Comment by bebraw** [comment]
I deployed a fixed version. I'm still a bit unsure about what to do with the anchors (i.e, `#foo` kind of link). Those could be either resolved against blog post url or removed. But at least most of the links should work as expected now. Thanks!

**Comment by Munter** [comment]
Looks lot better. I took another pass at it and get a lot fewer errors. Looks like there might be one more bug left. Links pointing to `'../foo'` from http://survivejs.com/blog/article get resolved to `'http://survivejs.com/foo'` in the xml file.

One example of this: http://survivejs.com/blog/2015-recap/ is linking to http://survivejs.com/blog/succeed-at-technical-books/ but the atom feed links to http://survivejs.com/succeed-at-technical-books/

**Comment by bebraw** [comment]
@Munter Thanks! I went through the links using your tool (great work!). The RSS should look better now.

I think I still might do something about anchors, but that's a smaller thing.
