### ISSUE TITLE
Make sure TOC is visible on low resolutions

### ISSUE THREAD

**Issue by bebraw** [survivejs/site#35]
Now TOC is hidden on low resolutions. Not ideal.

**Comment by bebraw** [comment]
Related comment:

> fix a hamburger menu the same way that the github sticker is?

**Comment by st-sloth** [comment]
Very difficult navigating the site on mobile without TOC.

**Comment by sapegin** [comment]
> fix a hamburger menu the same way that the github sticker is?

I guess this part is done already.

**Comment by sapegin** [comment]
How about something like this?

https://paul.kinlan.me/experiments-in-buildin-a-mobile-friendly-table-of-contents/

**Comment by bebraw** [comment]
Worth a go.
