### ISSUE TITLE
Make sure the site performs well on iOS (different versions)

### ISSUE THREAD

**Issue by bebraw** [survivejs/site#37]

**Comment by sapegin** [comment]
@bebraw Any particular issues?

**Comment by sapegin** [comment]
![image](https://user-images.githubusercontent.com/70067/34310506-368ffeee-e758-11e7-8d83-9ea6024117c6.jpg)

![image](https://user-images.githubusercontent.com/70067/34310511-3b0f45d8-e758-11e7-8aaf-b326fae8d5ad.jpg)

![image](https://user-images.githubusercontent.com/70067/34310516-4098cf1a-e758-11e7-8936-fd56d057f19c.jpg)

**Comment by bebraw** [comment]
Yeah, we could center it and make the site look nicer on lower resolutions. I think it’s better than it used to be, though.

**Comment by sapegin** [comment]
I’ve updated my comment — there should be three different images ;-£

**Comment by sapegin** [comment]
Read the free version — Read for free?

**Comment by bebraw** [comment]
Yeah, I will change it to "Read for free". Good call.

**Comment by bebraw** [comment]
Ah, you changed it already. Great. 👍
