### ISSUE TITLE
Host on Netlify

### ISSUE THREAD

**Issue by bebraw** [survivejs/site#64]
This would give nicer feedback forms etc.

**Comment by sapegin** [comment]
What do you mean by “nicer feedback forms”?

**Comment by bebraw** [comment]
Now feedback (Contact button) goes throuh Google Forms and gets piped to a spreadsheet. Going through Netlify would make it possible to implement a nicer form.

**Comment by bebraw** [comment]
It's on Netlify now (Cloudflare in front). I'm not using much functionality yet but the experience should be better.
