### ISSUE TITLE
Highlight current book on all pages

### ISSUE THREAD

**Issue by sapegin** [survivejs/site#70]
Not just on the cover:

![image 2017-12-11 at 10 22 11 pm](https://user-images.githubusercontent.com/70067/33854372-cb89b73c-dec1-11e7-8f3f-f969d9d47bb0.png)

But I couldn‘t find sources for the menu.

**Comment by bebraw** [comment]
You can copy it over from https://github.com/survivejs-sites/components/blob/master/src/Navigation.js .

**Comment by bebraw** [comment]
`link.url === pathname` needs to become smarter.

**Comment by bebraw** [comment]
There's one problem with doing this. If we fix the link like that, how to get to the book index in a smart way? We would lose that link unless it's added to some other place. Any idea how to solve this?

**Comment by sapegin** [comment]
We should keep the link, just highlight it.

**Comment by bebraw** [comment]
Got it, maybe just bold then. Nice idea.

**Comment by sapegin** [comment]
Then we’ll have three styles ;-)

**Comment by bebraw** [comment]
Ok, bold + black. That's it. 👍
