### ISSUE TITLE
Try CSS Modules or CSS in JS for styling

### ISSUE THREAD

**Issue by sapegin** [survivejs/site#74]
Maybe not CSS Modules but seems like the easiest to migrate. Other ideas? 

Investigate ~~Styled Components~~, Emotion, JSS.

**Comment by bebraw** [comment]
I know CSS Modules would work. Easy to set up too.

Which css-in-js solution allows easy style extraction these days? Is there something particularly good for static sites?

**Comment by sapegin** [comment]
I can explore this a bit, I’m curious too ;-)

**Comment by bebraw** [comment]
Ok. css-in-js is acceptable as long as we can get a CSS file out of it neatly.

**Comment by sapegin** [comment]
I guess we may have issues with hot reload.

**Comment by sapegin** [comment]
https://medium.com/styled-components/the-simple-guide-to-server-side-rendering-react-with-styled-components-d31c6b2b8fbf
But they are rendering one page and extract styles for one page only. Not sure how it will work with multiple pages.

**Comment by sapegin** [comment]
https://github.com/emotion-js/emotion/blob/master/docs/extract-static.md

Emotion has something but it requires a Babel plugin.

**Comment by bebraw** [comment]
> Emotion has something but it requires a Babel plugin.

Babel is fine. That sounds promising. 👍

**Comment by sapegin** [comment]
Yeah, we can try couple of components.
