### ISSUE TITLE
Footer should be always below sidebar

### ISSUE THREAD

**Issue by sapegin** [survivejs/site#75]
![image 2017-12-11 at 10 38 18 pm](https://user-images.githubusercontent.com/70067/33855039-0915f4f6-dec4-11e7-8c0d-e563970da149.png)

Maybe sidebar is to tall, maybe we need to move books to the footer too.

**Comment by bebraw** [comment]
Yeah, that’s a good idea. Maybe just right to the blog posts neatly arranged.

**Comment by sapegin** [comment]
Which idea? ;-)

**Comment by bebraw** [comment]
I mean, simplifying the sidebar. Now it’s too noisy.
