### ISSUE TITLE
Weird scrollbars on Windows

### ISSUE THREAD

**Issue by sapegin** [survivejs/site#85]
![image](https://user-images.githubusercontent.com/70067/34981900-3bc8dbf6-faa9-11e7-96cf-675c1f3057ee.png)

![image](https://user-images.githubusercontent.com/70067/34981977-6da0d0ac-faa9-11e7-9bfd-efb254c1a6c6.png)

**Comment by bebraw** [comment]
We could set `overflow: auto` for those to fix it I think. For some reason the content doesn't fit...

**Comment by sapegin** [comment]
It already has auto (on `blockquote`) for some reason, and that's the issue ;-)

**Comment by bebraw** [comment]
Right. Maybe we have to go `overflow: none` then to hide. The real question why the hack was needed in the first place. It feels like a sizing issue.

**Comment by sapegin** [comment]
We just need to remove it and use default `visible` ;-)
