### ISSUE TITLE
Site content is cropped on Android

### ISSUE THREAD

**Issue by bebraw** [survivejs/site#93]
Report: https://survivejs.com/maintenance/introduction/#comment-3751393440 .

Maybe some margin bits. Something to investigate.

**Comment by sapegin** [comment]
This looks exactly like #91.

**Comment by bebraw** [comment]
Yeah, I wonder if it's some caching issue.

**Comment by sapegin** [comment]
Actually I can reproduce it on *that* page, not on Preface for example.

**Comment by sapegin** [comment]
I can reproduce it on this page locally: https://survivejs.com/maintenance/packaging/anatomy/ — will look into that.
